[package]
org = "ballerinax"
name = "health.fhir.r4utils.fhirpath"
version = "3.1.0"
distribution = "2201.12.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Utils", "FHIRPath"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"

