[package]
org = "ballerinax"
name = "health.fhir.r4utils.fhirpath"
version = "1.1.1"
distribution = "2201.7.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Utils", "FHIRPath"]
export = ["health.fhir.r4utils.fhirpath"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
