[package]
org = "ballerinax"
name = "health.fhir.r4.carinbb200"
version = "1.1.2"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "health_fhir_r4_carinbb200"]
export = ["health.fhir.r4.carinbb200"]

