[package]
org = "ballerinax"
name = "health.fhir.r4.carinbb200"
version = "2.0.0"
distribution = "2201.12.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "health_fhir_r4_carinbb200"]


