[package]
authors = ["Ballerina"]
distribution = "2201.12.2"
keywords = ["Healthcare", "FHIR", "R4", "health_fhir_r4_davincidrugformulary210"]
name = "health.fhir.r4.davincidrugformulary210"
org = "ballerinax"
version = "2.0.1"

