[package]
org = "ballerinax"
name = "health.fhir.r4"
version = "4.0.0"
distribution = "2201.6.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4",]

[[dependency]]
org = "ballerinax"
name = "health.base"
version = "1.0.3"
