[package]
org = "ballerinax"
name = "health.fhir.r4utils.deidentify"
version = "1.0.0"
distribution = "2201.12.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Utils", "deidentify"]
