[package]
org = "ballerinax"
name = "health.fhir.cds"
version = "1.1.2"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "CDS", "CRD"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.cds"]

