[package]
org = "ballerinax"
name = "health.fhir.cds"
version = "2.0.4"
distribution = "2201.12.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "CDS", "CRD"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"

