[package]
org = "ballerinax"
name = "health.fhir.r4.validator"
version = "6.0.1"
distribution = "2201.12.8"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Validator"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
