[package]
org = "ballerinax"
name = "health.fhir.r4.international401"
version = "2.2.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "International"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.international401"]

