[package]
org = "ballerinax"
name = "health.fhirr4"
version = "${project.version}"
distribution = "${ballerina.version}"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "service"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"

[build-options]
observabilityIncluded = true

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerinax"
artifactId = "fhirr4-native"
version = "${project.version}"
path = "./fhirr4-native-${project.version}.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.6.0"
