[package]
org = "ballerinax"
name = "health.fhirr4"
version = "${project.version}"
distribution = "${ballerina.version}"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "service"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"

[build-options]
observabilityIncluded = true

[platform.java11]
graalvmCompatible = true

# Todo: Remove this after the issue https://github.com/wso2-enterprise/wso2-integration-internal/issues/4657 is fixed.
[[dependency]]
name="data.csv"
org="ballerina"
version="0.8.1"

[[platform.java11.dependency]]
groupId = "io.ballerinax"
artifactId = "fhirr4-native"
version = "${project.version}"
path = "./fhirr4-native-${project.version}.jar"
