[package]
org = "ballerinax"
name = "health.fhir.r4.uscore400"
version = "2.0.0"
distribution = "2201.12.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "uscore400"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"


