[package]
org = "ballerinax"
name = "health.fhir.r4.terminology"
version = "4.0.1"
distribution = "2201.7.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Terminology"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.terminology"]

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "4.0.0"
