[package]
org = "ballerinax"
name = "health.fhir.r4.terminology"
version = "5.0.1"
distribution = "2201.12.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Terminology"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
