[package]
org = "ballerinax"
name = "health.fhir.r4.parser"
version = "4.1.1"
distribution = "2201.8.4"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Parser"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.parser"]

