[package]
org = "ballerinax"
name = "health.fhir.r4.parser"
version = "7.1.0"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Parser"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"


