[package]
org = "ballerinax"
name = "health.fhir.r4.parser"
version = "1.0.0"
distribution = "2201.7.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Parser"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.parser"]

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "4.0.0"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.international401"
version = "1.0.0"