[package]
org = "ballerinax"
name = "health.fhir.r4.uscore700"
version = "1.0.2"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "uscore700"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.uscore700"]
