[package]
org = "ballerinax"
name = "health.fhir.r4utils.ccdatofhir"
version = "1.0.2"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Utils", "CCDAtoFHIR"]
export = ["health.fhir.r4utils.ccdatofhir"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"

[[dependency]]
org = "ballerinax"
name="health.fhir.r4"
version="4.0.0"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.international401"
version = "1.0.0"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.uscore501"
version = "1.2.0"
