[package]
org = "ballerinax"
name = "health.fhir.r4.uscore700"
version = "3.0.1"
distribution = "2201.12.8"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "uscore700"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"


