[package]
org = "ballerinax"
name = "health.fhir.r4.uscore501"
version = "1.3.3"
distribution = "2201.9.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "USCore"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.uscore501"]

