[package]
org = "ballerinax"
name = "health.fhir.r4.aubase410"
version = "1.0.6"
distribution = "2201.6.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "AUBase"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.aubase410"]

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "3.0.0"
