name: daily-build-fhirtoccda

on:
  schedule:
    - cron: '15 20 * * *'    # 01:45 in LK time (GMT+5:30)
  workflow_dispatch:

jobs:
  build:
     uses: ./.github/workflows/daily-build-executor.yml
     secrets: inherit
     with:
      working_dir: utils/fhirtoccda
